import Head from "next/head";
import styles from "@/styles/Home.module.css";
import HeroSection from "@/Components/HeroSection/HeroSection";
import BrandsWorked from "@/Components/BrandsWorked/BrandsWorked";
import CoreProblems from "@/Components/CoreProblems/CoreProblems";
import CardStacking from "@/Components/CardStacking/CardStacking";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bimboo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="logo.png" />
      </Head>
      <main>
        <HeroSection />
        <BrandsWorked />
        <CoreProblems />
        <CardStacking />
      </main>
    </>
  );
}
