import React from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import HeroSection from "@/Components/HeroSection/HeroSection";
import BrandsWorked from "@/Components/BrandsWorked/BrandsWorked";
import CoreProblems from "@/Components/CoreProblems/CoreProblems";
import CardStacking from "@/Components/CardStacking/CardStacking";
import CaseStudy from "@/Components/CaseStudy/CaseStudy";
import TestimonialStack from "@/Components/Testimonial/TestimonialStack";
import Navbar from "@/Components/Navbar/Navbar";
import CoreProblemsNew from "@/Components/CoreProblems/CoreProblemsNew";
import GetInTouch from "@/Components/ GetInTouch/ GetInTouch";
import Footer from "@/Components/Footer/Footer";

export default function Home() {
   
  return (
    <>
      <Head>
        <title>Bimboo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="logo.svg" />
      </Head>
      <main data-scroll-container>
        <Navbar />
        <HeroSection />
        <BrandsWorked />
        <CoreProblemsNew/>
        <CardStacking />
        <CaseStudy />
        <TestimonialStack />
        <GetInTouch/>
        <Footer/>
      </main>
    </>
  );
}
